## -----------------------------------------------------
## openssl.
## Miscellaneous Functions
##
## @category  openssl
## @package   Includes
## @license Apache-2.0 <https://github.com/ojullien/pki/blob/master/LICENSE>
## -----------------------------------------------------

## -----------------------------------------------------
## Delay execution
## -----------------------------------------------------
pause () {
    echo -n "Press a key to continue..."
    read nothing
}
